name: Atualização Automática Focus

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch: 
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install pandas requests

      - name: Executar Script de Inteligência
        run: python analise_focus.py

      - name: Guardar as atualizações
        run: |
          git config --global user.name 'Vitória Amaral Bot'
          git config --global user.email 'vitoriaamaral.br@gmail.com'
          git add .
          git commit -m "Automação: Dados Focus Atualizados" || echo "Sem alterações"
          git push
